// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/pleum/hexgo/cmd/api/internal/app"
)

// Injectors from wire.go:

func InitializeContainer() (Container, func(), error) {
	fiberApp, cleanup, err := app.NewFiberApp()
	if err != nil {
		return Container{}, nil, err
	}
	container := Container{
		App: fiberApp,
	}
	return container, func() {
		cleanup()
	}, nil
}
